name = "GKMtest"
uuid = "f0a7beec-ce01-462c-9058-91af0b9134dc"
authors = ["Giosuè Muratore <muratore.g.e@gmail.com >", "Daniel Holmes <daniel.holmes@ist.ac.at>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Combinatorics = "1.0.2"
Oscar = "1.2.2"
ProgressMeter = "1.10.2"
Test = "1.11.0"
